apiVersion: v1
kind: ServiceMesh
metadata:
  name: luminaire-solar-api
spec:
  mesh:
    authentication:
      bypassRoutes:
        # Original routes (kept for backward compatibility)
        - path: /user
          methods: [GET]
        - path: /info
          methods: [GET]
        - path: /products
          methods: [GET]
        - path: /summary/:systemId
          methods: [GET]
        - path: /forecast/:systemId
          methods: [GET]
        - path: /healthcheck
          methods: [GET]
          
        # API-prefixed original routes
        - path: /api/user
          methods: [GET]
        - path: /api/info
          methods: [GET]
        - path: /api/products
          methods: [GET]
        - path: /api/summary/:systemId
          methods: [GET]
        - path: /api/forecast/:systemId
          methods: [GET]
        - path: /api/healthcheck
          methods: [GET]
          
        # New Salesforce routes with API prefix
        - path: /api/salesforce/user
          methods: [GET]
        - path: /api/salesforce/info
          methods: [GET]
        - path: /api/salesforce/products
          methods: [GET]
        - path: /api/salesforce/summary/:systemId
          methods: [GET]
        - path: /api/salesforce/forecast/:systemId
          methods: [GET]
          
        # Standard API product routes
        - path: /api/products
          methods: [GET]
        - path: /api/products/:id
          methods: [GET]
          
      # Note: Wildcards not supported before GA, only explicit paths included