import fp from 'fastify-plugin';
import { OpenAI } from 'openai';
import { config } from '../config.js';

export default fp(async (fastify) => {
  const client = new OpenAI({
    apiKey: config.DYNO_INTEROP_TOKEN,
    baseURL: config.DYNO_INTEROP_BASE_URL,
  });
  fastify.decorate('ai', {
    executeCompletion: async (question) => {
      const PROMPT = `
<<<<<<< HEAD
      If plotting questions are asked, use matplotlib for plotting. Upload the PNG to S3 and return the image as a pre-signed S3 URL that expires after 18 hours.

      Always fetch the database schema before attempting to query the database.

      Energy units should be in kilowatt-hours (kWh).

      Give specific answers to the questions asked. Don't guess or provide vague answers. Keep the responses concise. Don't respond with the operations performed. Just give the answer.

      Always respond in markdown format. Convert newlines to <br> tags, paragraphs to <p>. When giving numbers use <strong>, when returning code, use <code> blocks.

      Make sure you install packages such as boto3 and matplotlib in the Python code execution tool before running the code.
      
      All the products information can be found in the database.
      
      If asking general questions about Luminaire Solar, visit https://luminaire.ukoreh.com/about for the answer.
      
      Do not navigate to any other website.
      
      If the question is not related to energy production or consumption data or products, respond with "I'm sorry, I can only answer questions about Luminaire Solar."

=======
      Always fetch the database schema before attempting to query the database.
      Make sure you install packages such as pandas and matplotlib in the Python code execution tool before running the code.
      If calculation questions are asked, use pandas for data manipulation but don't generate random data.
      If plotting questions are asked, use matplotlib for plotting and return the base64 encoded png image. 
      Energy units should be in kilowatt-hours (kWh).
      
      Always respond in markdown format. 
      Convert newlines to <br> tags, paragraphs to <p>. 
      When giving numbers use <strong>. 
      When returning code, use <code> blocks.

      If a base64 png image was generated by the Python code, return it as an <img> tag.
      Do not base64 encode ASCII output.
      
      All the products information can be found in the database.
      
      If asking general questions about Lumina Solar, visit https://lumina.ukoreh.com/about for the answer.
      Do not navigate to any other website.
      
      Give specific answers to the questions asked. Don't guess or provide vague answers. Keep the responses concise. Don't respond with the operations performed. Just give the answer.
      If the question is not related to energy production or consumption data or products, respond with "I'm sorry, I can only answer questions about Lumina Solar."

>>>>>>> c5ac68a (improve prompt and add web browsing support)
      Question: ${question}
      `;
      return client.chat.completions.create({
        model: 'claude-3-5-sonnet',
        messages: [
          {
            role: 'user',
            content: PROMPT,
          },
        ],
        tools: [
          {
            type: 'heroku_tool',
            function: 'database_get_schema',
            runtime_params: {
              target_app_name: config.APP_NAME,
              tool_params: {
                db_attachment: config.DATABASE_ATTACHMENT,
              },
            },
          },
          {
            type: 'heroku_tool',
            function: 'database_run_query',
            runtime_params: {
              target_app_name: config.APP_NAME,
              tool_params: {
                db_attachment: config.DATABASE_ATTACHMENT,
              },
            },
          },
          {
            type: 'heroku_tool',
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> c5ac68a (improve prompt and add web browsing support)
            function: 'web_browsing_multi_page',
          },
          {
            type: 'heroku_tool',
<<<<<<< HEAD
=======
>>>>>>> 828e013 (add AI support)
=======
>>>>>>> c5ac68a (improve prompt and add web browsing support)
            function: 'code_exec_python',
          },
        ],
        tool_choice: 'auto',
        stream: true,
      });
    },
  });
});
